package com.jtristan.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONDICION_PAGO.
 */
public class CondicionPago {

    private Long id;
    private String condicion;
    private Double porcentaje;
    private Double valor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CondicionPago() {
    }

    public CondicionPago(Long id) {
        this.id = id;
    }

    public CondicionPago(Long id, String condicion, Double porcentaje, Double valor) {
        this.id = id;
        this.condicion = condicion;
        this.porcentaje = porcentaje;
        this.valor = valor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCondicion() {
        return condicion;
    }

    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    public Double getPorcentaje() {
        return porcentaje;
    }

    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }

    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
